######################################################################
# Automatically generated by qmake (3.0) Wed Aug 6 18:05:16 2014
######################################################################

TEMPLATE = app
TARGET = step09
INCLUDEPATH += .

include(../../../../../chocolaf/common_files/common.pro)

# Input
HEADERS += Line.h Doodle.h DrawWindow.h MainWindow.h
SOURCES += Line.cc Doodle.cc DrawWindow.cc MainWindow.cc step09.cc
RESOURCES += resources.qrc
