######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 15 08:50:12 2016
######################################################################

TEMPLATE = app
TARGET = sigslot2

include(../../common.pro)

# Input
SOURCES += sigslot2.cc
