######################################################################
# Automatically generated by qmake (3.1) Mon Nov 1 16:16:43 2021
######################################################################

TEMPLATE = app
TARGET = hello

include (../../common.pro)

# Input
SOURCES += hello.cc
