######################################################################
# Automatically generated by qmake (3.1) Sat Nov 6 11:32:08 2021
######################################################################

CONFIG += msys2
TEMPLATE = app
TARGET = HelloWorld

include (../common.pro)

# Input
SOURCES += main.cc
