######################################################################
# Automatically generated by qmake (3.0) Mon Aug 4 15:44:11 2014
######################################################################

TEMPLATE = app
TARGET = step01

include(../common.pro)

# Input
SOURCES += step01.cc

DISTFILES += \
  step01.py
