######################################################################
# Automatically generated by qmake (3.0) Mon Aug 4 15:44:11 2014
######################################################################

TEMPLATE = app
TARGET = step01
INCLUDEPATH += .
win32 {
  CONFIG += console
}
CONFIG += c++17
QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
SOURCES += step01.cc
