######################################################################
# Automatically generated by qmake (3.1) Wed Mar 31 09:09:26 2021
######################################################################

TEMPLATE = app
TARGET = sigSlot

include (../../common.pro)

# Input
SOURCES += main.cc \
  widget.cpp

HEADERS += \
  widget.h
