######################################################################
# Automatically generated by qmake (3.0) Wed Dec 27 19:49:58 2017
######################################################################

TEMPLATE = app
TARGET = tempConverter

include(../../common.pro)

# Input
HEADERS += tempConverter.hxx tempConverterDialog.hxx
SOURCES += main.cpp tempConverter.cpp tempConverterDialog.cpp
