######################################################################
# Automatically generated by qmake (3.0) Mon Aug 4 17:03:21 2014
######################################################################

TEMPLATE = app
TARGET = step02

include(../common.pro)

# Input
HEADERS += DrawWindow.h
SOURCES += DrawWindow.cc step02.cc
