######################################################################
# Automatically generated by qmake (3.0) Mon Aug 4 17:27:23 2014
######################################################################
TEMPLATE = app
TARGET = step03
INCLUDEPATH += .

include(../../../../../chocolaf/common_files/common.pro)

# Input
HEADERS += DrawWindow.h
SOURCES += DrawWindow.cc step03.cc
