######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 19 07:50:20 2015
######################################################################
TEMPLATE = app
TARGET = sigslot

include(../../common.pro)

# Input
SOURCES += sigslot.cc
