######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 25 00:57:07 2015
######################################################################

TEMPLATE = app
TARGET = first

include(../../common.pro)

# Input
SOURCES += first.cc
