######################################################################
# Automatically generated by qmake (3.1) Thu Nov 11 11:09:26 2021
######################################################################

TEMPLATE = app
TARGET = qtdir
include (../../common_console.pro)

# Input
SOURCES += qtdir.cpp
