######################################################################
# Automatically generated by qmake (3.1) Tue Dec 28 17:08:58 2021
######################################################################

CONFIG += msys2

TEMPLATE = app
TARGET = first
INCLUDEPATH += .

include(../../common_console.pro)

# Input
SOURCES += first.cc
