######################################################################
# Automatically generated by qmake (3.0) Tue Aug 5 17:56:32 2014
######################################################################

TEMPLATE = app
TARGET = step05
INCLUDEPATH += .

include(../../../../../chocolaf/common_files/common.pro)

# Input
HEADERS += DrawWindow.h Line.h
SOURCES += DrawWindow.cc Line.cc step05.cc
