######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 25 01:02:43 2015
######################################################################

TEMPLATE = app
TARGET = layout

include(../../common.pro)

# Input
SOURCES += layout.cc
