######################################################################
# Automatically generated by qmake (3.0) Wed Aug 6 18:05:16 2014
######################################################################

TEMPLATE = app
TARGET = step07
INCLUDEPATH += .
CONFIG += c++14
QT += core gui widgets

# Input
HEADERS += Doodle.h DrawWindow.h Line.h
SOURCES += Doodle.cc DrawWindow.cc Line.cc step07.cc
RESOURCES += resources.qrc
