######################################################################
# Automatically generated by qmake (3.1) Thu Nov 11 11:09:26 2021
######################################################################

TEMPLATE = app
TARGET = qtmap
include (../../common_console.pro)

# Input
SOURCES += qtmap.cc
