######################################################################
# Automatically generated by qmake (3.1) Sat Nov 6 11:32:08 2021
######################################################################

TEMPLATE = app
TARGET = palette

include (../common.pro)

# Input
SOURCES += palette.cc
