######################################################################
# Automatically generated by qmake (3.0) Wed Aug 6 18:05:16 2014
######################################################################

TEMPLATE = app
TARGET = step08
INCLUDEPATH += .
win32 {
	CONFIG += console
}
QT += core gui widgets
CONFIG += c++17

# Input
HEADERS += Line.h Doodle.h DrawWindow.h MainWindow.h 
SOURCES += Line.cc Doodle.cc DrawWindow.cc MainWindow.cc step08.cc
RESOURCES += resources.qrc
