######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 13 07:03:52 2016
######################################################################

TEMPLATE = app
TARGET = byteConverter

include(../../common.pro)

# Input
HEADERS += byteConverterDialog.hxx byteConverter.hxx
SOURCES += byteConverterDialog.cpp main.cpp
