######################################################################
# Automatically generated by qmake (3.0) Tue Aug 5 16:03:43 2014
######################################################################

TEMPLATE = app
TARGET = step04
INCLUDEPATH += .
win32 {
    CONFIG += console
}
CONFIG += c++14
QT += core gui widgets

# Input
HEADERS += DrawWindow.h
SOURCES += DrawWindow.cc step04.cc
