######################################################################
# Automatically generated by qmake (3.0) Tue Aug 5 18:55:56 2014
######################################################################

TEMPLATE = app
TARGET = step06
INCLUDEPATH += .

win32 {
    CONFIG += console
}
CONFIG += c++14
QT += core gui widgets

# Input
HEADERS += DrawWindow.h Line.h Doodle.h
SOURCES += DrawWindow.cc Line.cc Doodle.cc step06.cc
