######################################################################
# Automatically generated by qmake (3.0) Tue Aug 5 18:55:56 2014
######################################################################

TEMPLATE = app
TARGET = step06
INCLUDEPATH += .

include (../common.pro)

# Input
HEADERS += DrawWindow.h Line.h Doodle.h
SOURCES += DrawWindow.cc Line.cc Doodle.cc step06.cc
